build_from:
  aarch64: ghcr.io/home-assistant/debian-base/aarch64:debian-11
  amd64: ghcr.io/home-assistant/debian-base/amd64:debian-11
  armv7: ghcr.io/home-assistant/debian-base/armv7:debian-11
args:
  TEMPIO_VERSION: "2021.09.0"
labels:
  io.hass.type: "addon"
  io.hass.version: "1.0.13"