build_from:
  aarch64: ghcr.io/home-assistant/debian-base/aarch64:bullseye
  amd64: ghcr.io/home-assistant/debian-base/amd64:bullseye
  armv7: ghcr.io/home-assistant/debian-base/armv7:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  TEMPIO_VERSION: "2021.09.0"