name: "Geodnet Headless Console API"
version: "1.0.13"
slug: "geodnet_headless_console_api"
description: "API for Geodnet Console data with improved platform compatibility"
url: "https://github.com/h5kk/geodnet-headless-console-m1-api"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: application
stage: experimental
boot: auto
hassio_api: true
hassio_role: default
map:
  - share:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "API port (required)"
options:
  refresh_interval: 60
  inactivity_timeout: 5
  proxy_pass_host: true
  proxy_pass_real_ip: true
  log_level: debug
schema:
  refresh_interval: int
  inactivity_timeout: int
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)
image: "ghcr.io/{arch}-addon-geodnet-headless-console-api"