name: "Geodnet Headless Console API"
version: "1.0.13"
slug: "geodnet_headless_console_api"
description: "API for Geodnet Console data"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/h5kk/geodnet-headless-console-m1-api"
startup: application
boot: manual
init: false
watchdog: tcp://[HOST]:3000
ports:
  3000/tcp: 3000
webui: http://[HOST]:3000
options:
  refresh_interval: 60
  inactivity_timeout: 5
schema:
  refresh_interval: int(30,3600)
  inactivity_timeout: int(1,60)
stage: stable